name: Update RSS Daily

on:
  schedule:
    - cron: '0 3 * * *'  # Codziennie o 03:00 UTC
  workflow_dispatch:      # Pozwala odpalić ręcznie z GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Generate RSS feed
      run: python generate_rss.py

    - name: Commit and push
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "rss-bot"
        git config --global user.email "rss-bot@example.com"
        git add feed.xml
        git commit -m "Aktualizacja RSS: $(date -u)" || echo "Brak zmian"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git push
